# drone server 部署     
version: "2"
services:
    drone-server:
      image: drone/drone:1 #drone/drone:1.0.0-rc.6
      ports:
        - 80:80
        - 443:443
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/lib/drone:/data
      restart: always
      environment:
        - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID} 
        - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET} 
        - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
        - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
        - DRONE_TLS_AUTOCERT=false
        - DRONE_RUNNER_CAPACITY=8
        - DRONE_DEBUG=false
        - DRONE_LOGS_DEBUG=false
        - DRONE_GIT_ALWAYS_AUTH=false
        - DRONE_SECRET_SECRET=${DRONE_SECRET_SECRET} # drone server 部署     